// <auto-generated />
using AerialResources.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AerialResources.Migrations
{
    [DbContext(typeof(AerialResourcesContext))]
    [Migration("20180624223211_newone")]
    partial class newone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AerialResources.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("CourseID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("AerialResources.Models.Move", b =>
                {
                    b.Property<int>("MoveID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseID");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("PreReq");

                    b.Property<string>("VideoLink");

                    b.HasKey("MoveID");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("AerialResources.Models.Parent", b =>
                {
                    b.Property<int>("ParentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("ParentID");

                    b.ToTable("Parent");
                });

            modelBuilder.Entity("AerialResources.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Name");

                    b.Property<int>("ParentID");

                    b.Property<bool>("Status");

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("AerialResources.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentCourseID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseID");

                    b.Property<int>("StudentID");

                    b.HasKey("StudentCourseID");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("AerialResources.Models.TrapezeVideos", b =>
                {
                    b.Property<int>("VideoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("PreReqs");

                    b.Property<string>("Url");

                    b.HasKey("VideoID");

                    b.ToTable("TrapezeVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
